const fmt=n=>'Rp'+Number(n).toLocaleString('id-ID');
const seed=[{id:1,name:'Canva Pro',price:25000,cat:'Desain',status:'Aktif'},{id:2,name:'ChatGPT Plus',price:75000,cat:'AI Tools',status:'Aktif'},{id:3,name:'Netflix Premium',price:35000,cat:'Streaming',status:'Aktif'}];
function products(){return JSON.parse(localStorage.products||'null')||seed.map(x=>({...x,rating:4.9,sold:100,icon:x.name[0],desc:'Produk premium bergaransi'}))}
function saveProducts(p){localStorage.products=JSON.stringify(p)}
function orders(){return JSON.parse(localStorage.orders||'[]')}
function saveOrders(o){localStorage.orders=JSON.stringify(o)}
function show(page){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));document.getElementById(page).classList.remove('hidden');document.querySelectorAll('.menu a').forEach(x=>x.classList.remove('active'));event?.target?.classList.add('active');renderAll()}
function renderAll(){let os=orders(), ps=products();document.getElementById('totalProduk').textContent=ps.length;document.getElementById('totalOrder').textContent=os.length;document.getElementById('pending').textContent=os.filter(o=>o.status==='Menunggu').length;document.getElementById('revenue').textContent=fmt(os.filter(o=>o.status==='Selesai').reduce((a,b)=>a+b.price,0));document.getElementById('orderRows').innerHTML=os.slice(0,6).map(o=>`<tr><td>${o.id}<br><small>${o.buyer}</small></td><td>${o.product}</td><td>${fmt(o.price)}</td><td><span class="pill ${o.status==='Selesai'?'ok':''}">${o.status}</span></td></tr>`).join('')||'<tr><td colspan="4">Belum ada order</td></tr>';document.getElementById('productRows').innerHTML=ps.map(p=>`<tr><td>${p.name}</td><td>${p.cat}</td><td>${fmt(p.price)}</td><td>${p.status||'Aktif'}</td><td><button class="btn ghost" onclick="editProduct(${p.id})">Edit</button></td></tr>`).join('');document.getElementById('manageOrders').innerHTML=os.map(o=>`<div class="card"><b>${o.id}</b> <span class="pill ${o.status==='Selesai'?'ok':''}">${o.status}</span><p>${o.product} - ${fmt(o.price)}</p><p>Pembeli: ${o.buyer} (${o.contact})</p><button class="btn green" onclick="approve('${o.id}')">Approve</button> <button class="btn red" onclick="rejectOrder('${o.id}')">Reject</button></div>`).join('')||'<div class="card">Belum ada order masuk dari website.</div>'}
function approve(id){let acc=prompt('Masukkan data akun/license untuk pembeli:','Email: premium@mail.com\nPassword: 123456');let os=orders();let o=os.find(x=>x.id===id);o.status='Selesai';o.account=acc||'';saveOrders(os);renderAll()}
function rejectOrder(id){let os=orders();let o=os.find(x=>x.id===id);o.status='Ditolak';saveOrders(os);renderAll()}
function addProduct(){let ps=products();let name=document.getElementById('pname').value, price=+document.getElementById('pprice').value, cat=document.getElementById('pcat').value;if(!name||!price)return alert('Lengkapi produk');ps.push({id:Date.now(),name,price,cat,status:'Aktif',rating:4.9,sold:0,icon:name[0],desc:'Produk premium bergaransi'});saveProducts(ps);renderAll();alert('Produk ditambahkan')}
function editProduct(id){let ps=products(),p=ps.find(x=>x.id==id);let price=prompt('Harga baru',p.price);if(price){p.price=+price;saveProducts(ps);renderAll()}}
document.addEventListener('DOMContentLoaded',renderAll)
