const seedProducts=[
{id:1,name:'Canva Pro',cat:'Desain',price:25000,rating:4.9,sold:245,icon:'Canva',desc:'Full premium, akun private, garansi 30 hari, proses 1-5 menit.'},
{id:2,name:'ChatGPT Plus',cat:'AI Tools',price:75000,rating:4.8,sold:187,icon:'GPT',desc:'Akses premium AI tools, garansi, cocok untuk kerja dan belajar.'},
{id:3,name:'Netflix Premium',cat:'Streaming',price:35000,rating:4.9,sold:321,icon:'N',desc:'Streaming premium kualitas HD, garansi sesuai paket.'},
{id:4,name:'Spotify Premium',cat:'Musik',price:20000,rating:4.9,sold:162,icon:'♫',desc:'Dengarkan musik tanpa iklan, akun premium bergaransi.'},
{id:5,name:'YouTube Premium',cat:'Streaming',price:18000,rating:4.8,sold:89,icon:'▶',desc:'YouTube tanpa iklan dan bisa background play.'},
{id:6,name:'Disney+ Hotstar',cat:'Streaming',price:25000,rating:4.7,sold:76,icon:'D+',desc:'Paket streaming film dan series premium.'},
{id:7,name:'CapCut Pro',cat:'Desain',price:20000,rating:4.9,sold:133,icon:'CC',desc:'Template dan fitur editing pro.'},
{id:8,name:'Adobe Photoshop',cat:'Desain',price:30000,rating:4.8,sold:64,icon:'Ps',desc:'Akses editing profesional.'}
];
const reviews=[['Ahmad Fauzi','Proses cepat banget, 2 menit sudah dikirim. Recommended!'],['Rina Amelia','Akun aman, garansi work. Makasih seller!'],['Budi Santoso','Mantap, harga murah kualitas premium.']];
const fmt=n=>'Rp'+Number(n).toLocaleString('id-ID');
function getProducts(){return JSON.parse(localStorage.products||'null')||seedProducts}
function setProducts(p){localStorage.products=JSON.stringify(p)}
function getOrders(){return JSON.parse(localStorage.orders||'[]')}
function setOrders(o){localStorage.orders=JSON.stringify(o)}
function renderProducts(cat='Semua'){const el=document.querySelector('#products'); if(!el)return; const ps=getProducts().filter(p=>cat==='Semua'||p.cat===cat); el.innerHTML=ps.map(p=>`<div class="card"><div class="productIcon">${p.icon}</div><h3>${p.name}</h3><div><span class="stars">★</span> ${p.rating} <span class="muted">(${p.sold})</span></div><div class="muted">Akun Private • Garansi 30 Hari</div><div class="price">${fmt(p.price)} <span class="muted" style="font-size:14px">/ bulan</span></div><button class="btn" onclick="openProduct(${p.id})">Beli Sekarang</button></div>`).join('')}
function openProduct(id){const p=getProducts().find(x=>x.id==id); document.querySelector('#modal').classList.add('show'); document.querySelector('#modalContent').innerHTML=`<button class="btn ghost" onclick="closeModal()">Tutup</button><div class="two"><div class="card"><div class="productIcon" style="width:140px;height:140px">${p.icon}</div><h1>${p.name}</h1><div><span class="stars">★★★★★</span> ${p.rating} (${p.sold} Review)</div><h2>${fmt(p.price)} <span class="muted">/ bulan</span></h2><p class="muted">${p.desc}</p><ul><li>Full Premium</li><li>Akun Private</li><li>Garansi 30 Hari</li><li>Proses 1-5 Menit</li></ul><button class="btn" onclick="checkout(${p.id})">Beli Sekarang</button></div><div class="card"><h3>Review Pembeli</h3>${reviews.map(r=>`<div style="border-bottom:1px solid var(--line);padding:14px 0"><b>${r[0]}</b><div class="stars">★★★★★</div><p class="muted">${r[1]}</p></div>`).join('')}</div></div>`}
function closeModal(){document.querySelector('#modal').classList.remove('show')}
function checkout(id){const p=getProducts().find(x=>x.id==id); document.querySelector('#modalContent').innerHTML=`<button class="btn ghost" onclick="closeModal()">Tutup</button><h2>Checkout</h2><div class="two"><div><div class="paybox"><b>Pesanan</b><p>${p.name}</p><h2>${fmt(p.price)}</h2></div><div class="field"><label>Nama Pembeli</label><input id="buyer" placeholder="Nama kamu"></div><div class="field"><label>WhatsApp / Email</label><input id="contact" placeholder="0812xxxx / email"></div><div class="field"><label>Metode Pembayaran</label><select id="method"><option>QRIS</option><option>Transfer Bank</option><option>DANA/OVO/Gopay</option></select></div></div><div><div class="paybox"><h3>QRIS Pembayaran</h3><p class="muted">Scan QRIS atau transfer manual sesuai nominal.</p><div class="qris">QRIS</div><p class="muted">BCA 123456789 a/n Sheikoshop</p><div class="field"><label>Upload Bukti Pembayaran</label><input id="proof" type="file"></div><button class="btn" onclick="submitOrder(${p.id})">Kirim Bukti Pembayaran</button></div></div></div>`}
function submitOrder(id){const p=getProducts().find(x=>x.id==id); const order={id:'INV-'+Date.now(),product:p.name,price:p.price,buyer:buyer.value||'Pembeli',contact:contact.value||'-',method:method.value,status:'Menunggu',date:new Date().toLocaleString('id-ID'),account:''}; const orders=getOrders();orders.unshift(order);setOrders(orders); document.querySelector('#modalContent').innerHTML=`<h2>Detail Pesanan</h2><div class="card"><h3>${order.id}</h3><div class="pill">Menunggu Verifikasi</div><div class="orderStatus"><div class="step">Pesanan Dibuat</div><div class="step">Menunggu Pembayaran Diverifikasi Admin</div><div class="step">Data akun akan muncul setelah disetujui</div></div><p class="muted">Simpan nomor invoice ini.</p><button class="btn" onclick="closeModal()">Selesai</button></div>`}
document.addEventListener('DOMContentLoaded',()=>{renderProducts();document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');renderProducts(t.textContent)})});
